### ISSUE TITLE
Complex Dict Support

### ISSUE THREAD

**Issue by DaveL17** [gmr/flatdict#5]
Great module.  Ran across this error when trying to flatten a JSON return from Weather Underground:

```
http://api.wunderground.com/api/API_KEY/conditions/q/CA/San_Francisco.json

Traceback (most recent call last):
  File "plugin.py", line 208, in getJSON
  File "/Library/..../flatdict.py", line 28, in __init__
  File "/Library/..../flatdict.py", line 74, in __setitem__
  File "/Library/..../flatdict.py", line 28, in __init__
  File "/Library/..../flatdict.py", line 74, in __setitem__
  File "/Library/..../flatdict.py", line 28, in __init__
  File "/Library/..../flatdict.py", line 83, in __setitem__
<type 'exceptions.TypeError'>: Top level node is not a FlatDict: country
```

Not sure whether this might be related to #2 or #3.

**Comment by gmr** [comment]
This should be resolved in 2.0
